# Generated by Django 5.1.2 on 2024-10-16 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='email',
            new_name='apt',
        ),
    ]
